---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "14.04"

inputs:
  - name: proto-pipelines
  - name: java-app-release
  - name: java-app-manifest

outputs:
  - name: prepare-release

params:
  CONFIG:

run:
  path: proto-pipelines/tasks/prepare-release.sh
